spring:
  data:
    mongodb:
        host: mongodb
        uri: mongodb+srv://Cluster47748:Z3NtRlJKVW9B@cluster47748.g8qeokq.mongodb.net/RouteService?retryWrites=true&w=majority
        port: 27017
  mvc:
    pathMatch:
      matching-strategy: ant_path_matcher
  application:
    name: route-service

  cloud:
    config:
      enabled: false
google-api: AIzaSyCQwQwxiJWDleZNmt-jllujxMw7yhRviRs
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://ec2-3-91-189-171.compute-1.amazonaws.com:8020/eureka/
#
#
#
