spring:
  data:
    mongodb:
        host: mongodb
        uri: mongodb+srv://Cluster47748:Z3NtRlJKVW9B@cluster47748.g8qeokq.mongodb.net/RouteService?retryWrites=true&w=majority
        port: 27017
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




  application:
    name: route-service
google-api: AIzaSyCQwQwxiJWDleZNmt-jllujxMw7yhRviRs
